/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/jzBarCharts/BarChart.vue')['default']
    BringGoodsRankList: typeof import('./components/jzBarCharts/BringGoodsRankList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/jzLineCharts/LineChart.vue')['default']
    TendencyLineChart: typeof import('./components/jzLineCharts/TendencyLineChart.vue')['default']
  }
}
